#+title: Config

* Table of Contents :toc:
- [[#doom-settings][Doom Settings]]
  - [[#theme][Theme]]
  - [[#font][Font]]
  - [[#window-title][Window title]]
  - [[#sensible-defaults][Sensible Defaults]]
- [[#keybindings][Keybindings]]
  - [[#comment-line][Comment Line]]
  - [[#toggle-bindings][Toggle bindings]]
  - [[#evil-mode][Evil mode]]
  - [[#workspace][Workspace]]
- [[#markdown][Markdown]]
  - [[#headers][Headers]]
  - [[#toggle-markdown-view][Toggle Markdown View]]
- [[#org][Org]]
  - [[#basic-settings][Basic Settings]]
  - [[#headers-1][Headers]]
  - [[#org-modern][Org modern]]
  - [[#org-roam-ui][Org roam ui]]
  - [[#org-appear][Org appear]]
  - [[#lsp-support-in-src-block][LSP support in src block]]
  - [[#org-agenda][Org Agenda]]
  - [[#org-startup][Org Startup]]
- [[#package][Package]]
  - [[#which-key][Which-key]]
  - [[#olivetti-mode][Olivetti mode]]

* Doom Settings
** Theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-monokai-spectrum)
#+end_src
** Font
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 17))
#+end_src
** Window title
#+begin_src emacs-lisp
(setq frame-title-format
      '(""
        (:eval
         (if (string-match-p (regexp-quote (or (bound-and-true-p org-roam-directory) "\u0000"))
                             (or buffer-file-name ""))
             (replace-regexp-in-string
              ".*/[0-9]*-?" "☰ "
              (subst-char-in-string ?_ ?\s buffer-file-name))
           "%b"))
        (:eval
         (when-let ((project-name (and (featurep 'projectile) (projectile-project-name))))
           (unless (string= "-" project-name)
             (format (if (buffer-modified-p)  " ◉ %s" "  ●  %s") project-name))))))
#+end_src
** Sensible Defaults
#+begin_src emacs-lisp
(setq confirm-kill-emacs nil)        ;; Don't confirm on exit
(setq display-line-numbers-type 'relative)
(setq doom-big-font-mode 1)
(setq flycheck-mode 1)
(setq auto-save-default t)
(setq delete-by-moving-to-trash t)
(save-place-mode 1)
#+end_src
* Keybindings
** Comment Line
#+begin_src emacs-lisp
(map! :leader
      :desc "Comment line" "-" #'comment-line)
#+end_src
** Toggle bindings
#+begin_src emacs-lisp
(map! :leader
      (:prefix ("t" . "toggle")
       :desc "Toggle line highlight in frame" "h" #'hl-line-mode
       :desc "Toggle bovine grammar mode"     "b" #'bovine-grammar-mode
       :desc "Toggle org-mode"                "O" #'org-mode
       :desc "Toggle line highlight globally" "H" #'global-hl-line-mode
       :desc "Toggle line numbers"            "l" #'doom/toggle-line-numbers
       :desc "Toggle truncate lines"          "t" #'toggle-truncate-lines
       :desc "Toggle olivetti mode"           "o" #'olivetti-mode
       :desc "Toggle Org Roam UI"             "n" #'org-roam-ui-mode
))
(map! :leader
       :desc "Toggle treemacs"                "e" #'+treemacs/toggle
       :desc "Tangle file"                    "l" #'org-babel-tangle
)
(map! :i
        "C-i" #'up-list
        "C-M-i" #'backward-up-list)
(map! :leader
      (:prefix ("o" . "open here")
       :desc "Open eshell here"    "e" #'+eshell/here
))
#+end_src
** Evil mode
#+begin_src emacs-lisp
(map! :n "g s" #'evil-surround-change)
#+end_src
** Workspace
#+begin_src emacs-lisp
(map! :leader
       :desc "Switch to workspace 1"          "1" #'+workspace/switch-to-0
       :desc "Switch to workspace 2"          "2" #'+workspace/switch-to-1
       :desc "Switch to workspace 3"          "3" #'+workspace/switch-to-2
       :desc "Switch to workspace 4"          "4" #'+workspace/switch-to-3
       :desc "Switch to workspace 5"          "5" #'+workspace/switch-to-4
       :desc "Switch to workspace 6"          "6" #'+workspace/switch-to-5
       :desc "Switch to workspace 7"          "7" #'+workspace/switch-to-6
       :desc "Switch to workspace 8"          "8" #'+workspace/switch-to-7
)
#+end_src
* Markdown
This sets the font size for each markdown header level.  Having variable font sizes in a markdown outline makes it visually appealing and more readable.
** Headers
#+begin_src emacs-lisp
(custom-set-faces
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))

 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.6))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.5))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.4))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-5 ((t (:inherit markdown-header-face :height 1.2))))
 '(markdown-header-face-6 ((t (:inherit markdown-header-face :height 1.1)))))
#+end_src

** Toggle Markdown View
A custom function to toggle between standard 'markdown-mode' and 'markdown-view-mode'.  Custom functions in Emacs should be named as "prefix/name-of-function" to make it clear that the function is custom and not a standard Emacs function.  In my case, I begin all my custom functions with 'dt'.

#+begin_src emacs-lisp
(defun dt/toggle-markdown-view-mode ()
  "Toggle between `markdown-mode' and `markdown-view-mode'."
  (interactive)
  (if (eq major-mode 'markdown-view-mode)
      (markdown-mode)
    (markdown-view-mode)))
#+end_src

* Org
** Basic Settings
#+begin_src emacs-lisp
(setq org-modern-table-vertical 1)
(defun just-agenda()
  (org-agenda-list)
  (delete-other-windows))
(setq org-modern-table t)
(add-hook 'org-mode-hook #'hl-todo-mode)
(after! org
    (setq org-agenda-span 'day)
    (setq org-super-agenda-mode 1))
(setq org-directory "~/org" ; Let's put files here.
	      org-agenda-files (list org-directory)                  ; Seems like the obvious place.
	      org-use-property-inheritance t                         ; It's convenient to have properties inherited.
	      org-log-done 'time                                     ; Having the time a item is done sounds convenient.
	      org-list-allow-alphabetical t                          ; Have a. A. a) A) list bullets.
	      org-catch-invisible-edits 'smart                       ; Try not to accidently do weird stuff in invisible regions.
	      org-export-with-sub-superscripts '{}                   ; Don't treat lone _ / ^ as sub/superscripts, require _{} / ^{}.
	      org-export-allow-bind-keywords t                       ; Bind keywords can be handy
	      org-image-actual-width '(0.9))
#+end_src

** Headers
This sets the font size for each Org header level.  Having variable font sizes in an Org outline makes it visually appealing and more readable.
#+begin_src emacs-lisp
(custom-theme-set-faces!
'doom-monokai-spectrum
'(org-level-4 :inherit outline-3 :height 1.2)
'(org-level-3 :inherit outline-3 :height 1.3)
'(org-level-2 :inherit outline-2 :height 1.4)
'(org-level-1 :inherit outline-1 :height 1.5)
'(org-document-title  :height 2.8 :bold t :underline nil))
#+end_src


** Org modern
#+begin_src emacs-lisp
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (set-face-attribute 'org-modern-label nil :height 1.3) ;; This make the TODO, WAIT, DONE, etc more readable
  (setq org-modern-star '("◉" "○" "◆" "▶" )
        org-modern-table-vertical 1
        org-modern-todo-faces -1
        org-modern-table-horizontal 0.2
        org-modern-list '((43 . "➤")
                          (45 . "–")
                          (42 . "•"))
        org-modern-todo-faces
        '(("TODO" :inverse-video t :inherit org-todo          :foreground "#A3BE8C" :weight bold)
          ("PROJ" :inverse-video t :inherit +org-todo-project :foreground "#88C0D0" :weight bold)
          ("HOLD" :inverse-video t :inherit +org-todo-onhold  :foreground "#8FBCBB" :weight bold)
          ("WAIT" :inverse-video t :inherit +org-todo-onhold  :foreground "#81A1C1" :weight bold)
          ("KILL" :inverse-video t :inherit +org-todo-cancel  :foreground "#EBCB8B" :weight bold)
          ("NO"   :inverse-video t :inherit +org-todo-cancel  :foreground "#30343d" :weight bold))
        org-modern-footnote
        (cons nil (cadr org-script-display))
        org-modern-block-fringe nil
        org-modern-block-name
        '((t . t)
          ("src" "»" "«")
          ("example" "»–" "–«")
          ("quote" "❝" "❞")
          ("export" "⏩" "⏪"))
        org-modern-progress nil
        org-modern-priority nil
        org-modern-horizontal-rule (make-string 36 ?─)
        org-modern-keyword
        '((t . t)
            ("title" . "📝")
            ("subtitle" . "📄")
            ("author" . "👤")
            ("email" . "📧")
            ("date" . "📅")
            ("property" . "🏷️")
            ("options" . "⚙️")
            ("startup" . "🚀")
            ("macro" . "🪄")
            ("bind" . "⌨️")
            ("bibliography" . "📚")
            ("print_bibliography" . "🖨️")
            ("cite_export" . "📤")
            ("include" . "📥")
            ("setupfile" . "🛠️")
            ("html_head" . "🔝")
            ("html" . "🌐")
            ("latex_class" . "📜")
            ("latex_class_options" . "🎛️")
            ("latex_header" . "🔝")
            ("latex_header_extra" . "➕")
            ("latex" . "📄")
            ("beamer_theme" . "🎨")
            ("beamer_color_theme" . "🌈")
            ("beamer_font_theme" . "🔡")
            ("beamer_header" . "🔝")
            ("beamer" . "📽️")
            ("call" . "📣")
            ("name" . "📛")
            ("header" . "🔝")
            ("caption" . "💬")
            ("results" . "🏁")))
  (custom-set-faces! '(org-modern-statistics :inherit org-checkbox-statistics-todo)))
#+end_src

#+begin_src emacs-lisp
(modify-all-frames-parameters
 '((right-divider-width . 0)
   (internal-border-width . 0)))
(dolist (face '(window-divider
                window-divider-first-pixel
                window-divider-last-pixel))
  (face-spec-reset-face face)
  (set-face-foreground face (face-attribute 'default :background)))
(set-face-background 'fringe (face-attribute 'default :background))
(setq
 ;; Edit settings
 org-auto-align-tags nil
 org-tags-column 0
 org-catch-invisible-edits 'show-and-error
 org-special-ctrl-a/e t
 org-insert-heading-respect-content t

 ;; Org styling, hide markup etc.
 org-hide-emphasis-markers t
 org-pretty-entities t
 org-agenda-tags-column 0
 org-ellipsis " [...]")

(global-org-modern-mode)
#+end_src
** Org roam ui
#+begin_src emacs-lisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src
** Org appear
#+begin_src emacs-lisp
(use-package! org-appear
  :hook (org-mode . org-appear-mode)
  :config
  (setq org-appear-autoemphasis t
        org-appear-autosubmarkers t
        org-appear-autolinks nil)
  ;; for proper first-time setup, `org-appear--set-elements'
  ;; needs to be run after other hooks have acted.
  (run-at-time nil nil #'org-appear--set-elements))
#+end_src
** LSP support in src block
#+begin_src emacs-lisp
(cl-defmacro lsp-org-babel-enable (lang)
  "Support LANG in org source code block."
  (setq centaur-lsp 'lsp-mode)
  (cl-check-type lang string)
  (let* ((edit-pre (intern (format "org-babel-edit-prep:%s" lang)))
         (intern-pre (intern (format "lsp--%s" (symbol-name edit-pre)))))
    `(progn
       (defun ,intern-pre (info)
         (let ((file-name (->> info caddr (alist-get :file))))
           (unless file-name
             (setq file-name (make-temp-file "babel-lsp-")))
           (setq buffer-file-name file-name)
           (lsp-deferred)))
       (put ',intern-pre 'function-documentation
            (format "Enable lsp-mode in the buffer of org source block (%s)."
                    (upcase ,lang)))
       (if (fboundp ',edit-pre)
           (advice-add ',edit-pre :after ',intern-pre)
         (progn
           (defun ,edit-pre (info)
             (,intern-pre info))
           (put ',edit-pre 'function-documentation
                (format "Prepare local buffer environment for org source block (%s)."
                        (upcase ,lang))))))))
(defvar org-babel-lang-list
  '("bash" "sh" "nix" "emacs-lisp"))
(dolist (lang org-babel-lang-list)
  (eval `(lsp-org-babel-enable ,lang)))
#+end_src
** Org Agenda
*** Text Centering with Olivetti
 The wider a block of text spans, the more difficult it is to read. To solve this, a package called Olivetti was made. Once you install it from MELPA, it can be activated easily by calling ~M-x olivetti-mode~.

To automatically activate this upon opening org-agenda, you can define an open hook, and add it to the ~org-agenda-mode-hook~:
#+begin_src emacs-lisp
;; Function to be run when org-agenda is opened
(defun org-agenda-open-hook ()
  "Hook to be run when org-agenda is opened"
  (olivetti-mode))

;; Adds hook to org agenda mode, making follow mode active in org agenda
(add-hook 'org-agenda-mode-hook 'org-agenda-open-hook)
#+end_src
*** Show Only Relevant Information
I easily get overwhelmed by too much information. Personally, I think the default view of org agenda is too cluttered. This can be fixed quite easily with a few configuration variables. Firstly, I show only one day at a time, the current day:
#+begin_src emacs-lisp
;; Only show one day of the agenda at a time
(setq org-agenda-span 1
      org-agenda-start-day "+0d")
#+end_src
 You can go to the next day with the function ~org-agenda-later~, and the previous day with ~org-agenda-earlier~, which I have bound to ~]~ and ~[~ respectively.

If you utilize #+SCHEDULED and #+DEADLINE for your todo items, along with normal timestamps, the following variables will reduce duplicate entries (in case you have an item with multiple of these designations at a time):
#+begin_src emacs-lisp
;; Hide duplicates of the same todo item
;; If it has more than one of timestamp, scheduled,
;; or deadline information
(setq org-agenda-skip-timestamp-if-done t
      org-agenda-skip-deadline-if-done t
      org-agenda-skip-scheduled-if-done t
      org-agenda-skip-scheduled-if-deadline-is-shown t
      org-agenda-skip-timestamp-if-deadline-is-shown t)
#+end_src
I also personally find the ………. and time grid all over the place to be annoying, and those I disable via:
#+begin_src emacs-lisp
;; Ricing org agenda
(setq org-agenda-current-time-string "")
(setq org-agenda-time-grid '((daily) () "" ""))
#+end_src
 If you like having the time grid around, you can mess with the time values and time strings in ~org-agenda-time-grid~ instead of nuking the time grid:
 #+begin_src emacs-lisp
;; A minimal time grid instead
(setq org-agenda-time-grid '((daily) (600 1200 1800) "---" "-----"))
 #+end_src
**** Category Icons
If you go through all of your agenda files and give them unique categories with the #+CATEGORY keyword, you can add icons to each todo item by setting the ~org-agenda-category-icon-alist~. You’ll probably also want ~nerd-icons~ installed to utilize this to its full potential. This is mine:
#+begin_src emacs-lisp
;; Add icons!
(setq org-agenda-category-icon-alist
      `(("Teaching.p" ,(list (nerd-icons-faicon "nf-fa-graduation_cap" :height 0.8)) nil nil :ascent center)
        ("Family.s" ,(list (nerd-icons-faicon "nf-fa-home" :v-adjust 0.005)) nil nil :ascent center)
        ("Bard.p" ,(list (nerd-icons-faicon "nf-fa-music" :height 0.9)) nil nil :ascent center)
        ("Stories.s" ,(list (nerd-icons-faicon "nf-fa-book" :height 0.9)) nil nil :ascent center)
        ("Knowledge.p" ,(list (nerd-icons-faicon "nf-fa-database" :height 0.8)) nil nil :ascent center)
        ;; Material Design "person" is usually "account" in Nerd Fonts/MDI
        ("Personal.p" ,(list (nerd-icons-mdicon "nf-md-account" :height 0.9)) nil nil :ascent center)))
;; Remove category names and scheduling type from agenda view
(setq org-agenda-prefix-format '(
(agenda . "  %?-2i %t ")
 (todo . " %i %-12:c")
 (tags . " %i %-12:c")
 (search . " %i %-12:c")))
#+end_src
**** ~Todo~ Item Grouping with Org Super Agenda
#+begin_src emacs-lisp
(setq org-super-agenda-groups
       '(;; Each group has an implicit boolean OR operator between its selectors.

         ;; This is the first filter, anything found here
         ;; will be placed in this group
         ;; even if it matches following groups
         (:name " Overdue" ; Name
                :scheduled past ; Filter criteria
                :order 2 ; Order it should appear in agenda view
                :face 'error) ; Font face used for text

         ;; This is the second filter, anything not found
         ;; from the first filter, but found here,
         ;; will be placed in this group
         ;; even if it matches following groups
         (:name "Personal" ; Name
                :file-path "Personal" ; Filter criteria
                :order 3 ; Order it should appear in the agenda view
                :face 'error) ; Font faced used for text

         ;; Third filter..
         (:name "Work"  ; Name
                :file-path "Work" ; Filter criteria
                :order 3 ; Order it should appear in the agenda view
                :face 'error) ; Font face used for text

         ;; Fourth filter..
         (:name " Today "  ; Optionally specify section name
                :time-grid t ; Use the time grid
                :date today ; Filter criteria
                :scheduled today ; Another filter criteria
                :order 1 ; Order it should appear in the agenda view
                :face 'warning) ; Font face used for text
        )
)
(setq org-super-agenda-groups
       '(;; Each group has an implicit boolean OR operator between its selectors.
         (:name " Overdue "  ; Optionally specify section name
                :scheduled past
                :order 2
                :face 'error)

         (:name "Personal "
                :and(:file-path "Personal.p" :not (:tag "event"))
                :order 3)

         (:name "Family "
                :and(:file-path "Family.s" :not (:tag "event"))
                :order 3)

         (:name "Teaching "
                :and(:file-path "Teaching.p" :not (:tag "event"))
                :order 3)

         (:name "Music "
                :and(:file-path "Bard.p" :not (:tag "event"))
                :order 3)

         (:name "Writing "
                :and(:file-path "Author.p" :not (:tag "event"))
                :order 3)

         (:name "Learning "
                :and(:file-path "Knowledge.p" :not (:tag "event"))
                :order 3)

          (:name " Today "  ; Optionally specify section name
                :time-grid t
                :date today
                :scheduled today
                :order 1
                :face 'warning)))
;; Load org-modern
(with-eval-after-load 'org (global-org-modern-mode))
#+end_src
** Org Startup
#+begin_src emacs-lisp
(add-hook 'server-after-make-frame-hook 'org-agenda-list)
(setq initial-buffer-choice (lambda ()
    (org-super-agenda-mode 1)
    (org-agenda-list 1)
    (get-buffer "*Org Agenda*")))

#+end_src
* Package
** Which-key
#+begin_src emacs-lisp
(setq which-key-idle-delay 0.5) ;; I need the help, I really do
(setq which-key-allow-multiple-replacements t)
(after! which-key
  (pushnew!
   which-key-replacement-alist
   '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . "◂\\1"))
   '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . "◃\\1"))
   ))
#+end_src

** Olivetti mode
Who ever want lines in olives
#+begin_src emacs-lisp
(add-hook 'olivetti-mode-on-hook (lambda () (display-line-numbers-mode -1)))
(add-hook 'olivetti-mode-off-hook (lambda () (display-line-numbers-mode 1) (setq display-line-numbers-type 'relative)))
#+end_src
