###Start dbus ###
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
### kill active portals and restart them ###
exec-once = ~/lunix/resources/portal.sh # Try https://discourse.nixos.org/t/slow-application-startup/29857/14?u=quocjq
# Daemon
exec-once = emacs --daemon

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

